### ISSUE TITLE
Consider using django-eraserhead

### ISSUE THREAD

**Issue by sobolevn** [proofit404/mappers#117]
https://github.com/dizballanze/django-eraserhead

**Comment by proofit404** [comment]
It looks like an interesting idea!

At the moment I believe the `mappers` package will kill any reason to use it. Since `reader` fetches only fields required by the entity.

But if the entity itself requires fields that are not used in any story, maybe this is the time for a new entity with fewer fields?

That would be an interesting challenge.

Have a good day :tada: 

Best regards,
Artem.

**Comment by proofit404** [comment]
Superseded by https://github.com/proofit404/generics/issues/48
